version: '3.8'

services:
  mariadb:
    build: ./requirements/MariaDB
    container_name: mariadb
    expose: 
      - "3306"
    env_file:
      - .env
    networks: 
      - khalidnet
    volumes:
      - mysql_volume:/var/lib/mysql
    restart: always
   
      

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    expose:
      - "9000"
    env_file:
      - .env
    networks:
      - khalidnet
    volumes:
      - mywp_vol:/var/www/html/wordpress
    restart: always


  nginx:
    build: ./requirements/nginx
    container_name: nginx
    networks:
      - khalidnet
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - mywp_vol:/var/www/html/wordpress
    restart: always
    
  

volumes:
  mysql_volume:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mysql
  mywp_vol:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp

networks:
  khalidnet:
    driver: bridge